# Generated by Django 2.2.5 on 2019-09-23 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50)),
                ('fonction', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Docteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=50)),
                ('presentation', models.TextField(max_length=500)),
                ('facebook', models.URLField()),
                ('github', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
                ('image', models.ImageField(upload_to='images/docteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('sujet', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/hopital')),
                ('logo', models.ImageField(upload_to='images/hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('lien', models.URLField()),
                ('image', models.ImageField(upload_to='images/services')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_temoin', to='careapp.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Heure_travail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('jour', models.CharField(max_length=20)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hopital_concerne', to='careapp.Hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('jour', models.CharField(max_length=20)),
                ('heure', models.TimeField()),
                ('message', models.TextField()),
                ('docteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docteur_consult', to='careapp.Docteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='docteur',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hopital_medecin', to='careapp.Hopital'),
        ),
        migrations.AddField(
            model_name='docteur',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_medecin', to='careapp.Service'),
        ),
        migrations.AddField(
            model_name='client',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hopital_doctor', to='careapp.Hopital'),
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/cartes')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hopital_med', to='careapp.Hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
