# Generated by Django 2.2.5 on 2019-09-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='image',
            field=models.ImageField(upload_to='static/careapp/images/cartes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(upload_to='static/careapp/images/client'),
        ),
        migrations.AlterField(
            model_name='docteur',
            name='image',
            field=models.ImageField(upload_to='static/careapp/images/docteur'),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='image',
            field=models.ImageField(upload_to='static/careapp/images/hopital'),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='logo',
            field=models.ImageField(upload_to='static/careapp/images/hopital'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='static/careapp/images/services'),
        ),
    ]
