# Generated by Django 2.2.5 on 2019-09-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0003_auto_20190924_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formappointment',
            name='heure',
            field=models.CharField(max_length=50),
        ),
    ]
