# Generated by Django 2.2.5 on 2019-09-24 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0005_auto_20190924_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formappointment',
            name='docteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docteur_consult', to='careapp.Docteur'),
        ),
    ]
