# Generated by Django 2.2.5 on 2019-09-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0009_auto_20190924_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='image',
            field=models.ImageField(upload_to='images/cartes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='docteur',
            name='image',
            field=models.ImageField(upload_to='images/docteur'),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='image',
            field=models.ImageField(upload_to='images/hopital'),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='logo',
            field=models.ImageField(upload_to='images/hopital'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='images/services'),
        ),
    ]
